### ISSUE TITLE
Devcon2 demo

### ISSUE THREAD

**Issue by haadcode** [haadcode/orbit#100]
This is an issue to track Devcon2 demo of Orbit.

- [X] Orbit with uPort identities
- [ ] Comments system ( working title "Planet Express")

**Comment by haadcode** [comment]
For uPort, need to:
- [ ] Make a final build that will be used for the demo
- [ ] MAke final build available for download (via IPFS, ipfs.io)
- [ ] Discuss and coordinate with ConsenSys to make sure the uPort modules are public before Devcon
- [ ] Final tests for the browsers version
- [ ] Deploy browser version

**Comment by haadcode** [comment]
"Planet Express" work happens here: https://github.com/haadcode/orbit/tree/tests.

![screen shot 2016-09-08 at 15 29 30](https://cloud.githubusercontent.com/assets/7499694/18387829/35dfa182-769f-11e6-947a-f18e42078295.png)

## TODO
- "retweet" functionality ("pin")
    + needs its own post and react renderer (like Message or Reply)
- fix feed history lengths, ie. how many items to display at a time (need to do on UI side now)
- add "follow" button and data structure
- aggregate view
- uPort integration
- add user's location the header
- planet express bot that caches *everything*
- proper urls to access feeds
- ~~delete post~~
- ~~move reply input inline (under reply-to message)~~
- ~~somehow notify replied-to feed of a reply~~
- ~~move input field to the feed~~
- ~~per-feed view~~
- ~~use "golden" color generator option~~
- ~~add max-height to header~~
- ~~fix File width~~
- ~~change headr background and per-user settings data structure~~
- ~~post replies only to reply feed (not to your own feed)~~
- ~~Message inside Message --> Reply (don't display replyTo)~~
- ~~Move reply functionality from MessageStore to ReplyStore~~

**Comment by jbenet** [comment]
@haadcode i think this should be a different repo so other people can help and you dont have branches that cant merge into each other. Unless you want one executable to do everything? or this one repo to produce many executables?

**Comment by jbenet** [comment]
### visual feedback

![image](https://cloud.githubusercontent.com/assets/138401/18400644/cf2d82aa-76a4-11e6-9adb-e3965ac9b4aa.png)
